export type Rule = {
  pattern: RegExp;
  replace: string;
  reason: string;
  confidence?: number;
};

const defaultConfidence = 0.8;

export const spellcheckRules: Rule[] = [
  { pattern: /싫엇/g, replace: "싫었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /있엇/g, replace: "있었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /이엇/g, replace: "이었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬/g, replace: "됐", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫/g, replace: "됐", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되요/g, replace: "돼요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되서/g, replace: "돼서", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되있/g, replace: "돼 있", reason: "맞춤법", confidence: 0.6 },
  { pattern: /할수/g, replace: "할 수", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /알수/g, replace: "알 수", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /볼수/g, replace: "볼 수", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /있을수/g, replace: "있을 수", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /될거/g, replace: "될 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /없을거/g, replace: "없을 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /될꺼/g, replace: "될 거", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /할꺼/g, replace: "할 거", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /할께/g, replace: "할게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /드릴께/g, replace: "드릴게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /해볼께/g, replace: "해볼게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /하는거/g, replace: "하는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /있는거/g, replace: "있는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /같은거/g, replace: "같은 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /되는거/g, replace: "되는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /먹는거/g, replace: "먹는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /보는거/g, replace: "보는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /듣는거/g, replace: "듣는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /쓰는거/g, replace: "쓰는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /인거/g, replace: "인 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /거같/g, replace: "것 같", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /것같/g, replace: "것 같", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /놀리는거/g, replace: "놀리는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /할려고/g, replace: "하려고", reason: "맞춤법", confidence: 0.7 },
  { pattern: /하려고해/g, replace: "하려고 해", reason: "띄어쓰기", confidence: 0.7 },
  { pattern: /어떡해/g, replace: "어떻게", reason: "맞춤법(문맥 주의)", confidence: 0.4 },
  { pattern: /안되/g, replace: "안 돼", reason: "맞춤법(문맥 주의)", confidence: 0.5 },
  { pattern: /안돼다/g, replace: "안 되다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /안대/g, replace: "안 돼", reason: "맞춤법", confidence: 0.5 },
  { pattern: /웬지/g, replace: "왠지", reason: "맞춤법", confidence: 0.6 },
  { pattern: /왠만/g, replace: "웬만", reason: "맞춤법", confidence: 0.6 },
  { pattern: /됬어/g, replace: "됐어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬다/g, replace: "됐다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됐엇/g, replace: "됐었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /뭔가요/g, replace: "무엇인가요", reason: "표준어", confidence: 0.4 },
  { pattern: /이렇케/g, replace: "이렇게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /저렇케/g, replace: "저렇게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /그렇케/g, replace: "그렇게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /거같아/g, replace: "것 같아", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /거같은/g, replace: "것 같은", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /있을꺼/g, replace: "있을 거", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /없는거/g, replace: "없는 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /같았엇/g, replace: "같았었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /같앗/g, replace: "같았", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /생각햇/g, replace: "생각했", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /말햇/g, replace: "말했", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들어왓/g, replace: "들어왔", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /식어버렷/g, replace: "식어버렸", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /식어버렷고/g, replace: "식어버렸고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /저엇/g, replace: "저었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /있엇다/g, replace: "있었다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /같앗다/g, replace: "같았다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /생각햇다/g, replace: "생각했다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /말햇다/g, replace: "말했다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들어왓다/g, replace: "들어왔다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /식어버렷다/g, replace: "식어버렸다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /저엇다/g, replace: "저었다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /있엇어요/g, replace: "있었어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /같앗어요/g, replace: "같았어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /생각햇어요/g, replace: "생각했어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /말햇어요/g, replace: "말했어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들어왓어요/g, replace: "들어왔어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /식어버렷어요/g, replace: "식어버렸어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /저엇어요/g, replace: "저었어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /할듯/g, replace: "할 듯", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /될듯/g, replace: "될 듯", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /끊길듯/g, replace: "끊길 듯", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /할것/g, replace: "할 것", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /될것/g, replace: "될 것", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /있을것/g, replace: "있을 것", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /없을것/g, replace: "없을 것", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /울수/g, replace: "울 수", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /될수/g, replace: "될 수", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /될꺼야/g, replace: "될 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /할꺼야/g, replace: "할 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /있을꺼야/g, replace: "있을 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /없을꺼야/g, replace: "없을 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /되야/g, replace: "돼야", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되야지/g, replace: "돼야지", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /될려면/g, replace: "되려면", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /할려면/g, replace: "하려면", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /볼려면/g, replace: "보려면", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /될려고/g, replace: "되려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갈려고/g, replace: "가려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /올려고/g, replace: "오려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /볼려고/g, replace: "보려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /먹을려고/g, replace: "먹으려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /마실려고/g, replace: "마시려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /읍니다/g, replace: "습니다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /읍니까/g, replace: "습니까", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /않될/g, replace: "안 될", reason: "맞춤법", confidence: 0.6 },
  { pattern: /않돼/g, replace: "안 돼", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안돼요/g, replace: "안 돼요", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안돼서/g, replace: "안 돼서", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안돼도/g, replace: "안 돼도", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안돼야/g, replace: "안 돼야", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안됬/g, replace: "안 됐", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /안될꺼/g, replace: "안 될 거", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /됫어/g, replace: "됐어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫을/g, replace: "됐을", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫음/g, replace: "됐음", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬을/g, replace: "됐을", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬음/g, replace: "됐음", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됐읍니다/g, replace: "됐습니다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /어의없/g, replace: "어이없", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /왠일/g, replace: "웬일", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫지/g, replace: "됐지", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /돼써/g, replace: "됐어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되있어/g, replace: "돼 있어", reason: "맞춤법", confidence: 0.6 },
  { pattern: /되있었/g, replace: "돼 있었", reason: "맞춤법", confidence: 0.6 },
  { pattern: /되있을/g, replace: "돼 있을", reason: "맞춤법", confidence: 0.6 },
  { pattern: /되버렸/g, replace: "돼버렸", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되버리/g, replace: "돼버리", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되버릴/g, replace: "돼버릴", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /돼어/g, replace: "되어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되여/g, replace: "되어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬는데/g, replace: "됐는데", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫는데/g, replace: "됐는데", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬네요/g, replace: "됐네요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫네요/g, replace: "됐네요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬을거/g, replace: "됐을 거", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫을거/g, replace: "됐을 거", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /봣다/g, replace: "봤다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /봣어요/g, replace: "봤어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /봣어/g, replace: "봤어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /봣었/g, replace: "봤었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /봤엇/g, replace: "봤었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /봣을/g, replace: "봤을", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /못햇/g, replace: "못했", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /못햇어/g, replace: "못했어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /못햇다/g, replace: "못했다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /못햇음/g, replace: "못했음", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /못하겟/g, replace: "못하겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /하겟/g, replace: "하겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /가겟/g, replace: "가겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /되겟/g, replace: "되겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /살겟/g, replace: "살겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /먹겟/g, replace: "먹겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /할께요/g, replace: "할게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /드릴께요/g, replace: "드릴게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /해줄께요/g, replace: "해줄게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갈께요/g, replace: "갈게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /올께요/g, replace: "올게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /볼께요/g, replace: "볼게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /적을께요/g, replace: "적을게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갈께/g, replace: "갈게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /올께/g, replace: "올게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /볼께/g, replace: "볼게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /않을께/g, replace: "않을게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /있을께/g, replace: "있을게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /마춧/g, replace: "맞췄", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /맞출려/g, replace: "맞추려", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /맞출려고/g, replace: "맞추려고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /맞출께/g, replace: "맞출게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /맟춰/g, replace: "맞춰", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /맟췄/g, replace: "맞췄", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /맟추/g, replace: "맞추", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫다고/g, replace: "됐다고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬다고/g, replace: "됐다고", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬답/g, replace: "됐답", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫답/g, replace: "됐답", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬대/g, replace: "됐대", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫대/g, replace: "됐대", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬으니/g, replace: "됐으니", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫으니/g, replace: "됐으니", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들엇/g, replace: "들었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들엇다/g, replace: "들었다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들엇어/g, replace: "들었어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /들엇어요/g, replace: "들었어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /썼엇/g, replace: "썼었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /썻다/g, replace: "썼다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /썻어/g, replace: "썼어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /썻어요/g, replace: "썼어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /썻을/g, replace: "썼을", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /왓다/g, replace: "왔다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /왓어요/g, replace: "왔어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /왓어/g, replace: "왔어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /왓었/g, replace: "왔었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /왔엇/g, replace: "왔었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갓다/g, replace: "갔다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갓어요/g, replace: "갔어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갓어/g, replace: "갔어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갓을/g, replace: "갔을", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갔엇/g, replace: "갔었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /갓겟/g, replace: "갔겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /줄알아/g, replace: "줄 알아", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /줄알았/g, replace: "줄 알았", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /줄알고/g, replace: "줄 알고", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /줄알았어/g, replace: "줄 알았어", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /같을꺼/g, replace: "같을 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /같을거/g, replace: "같을 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /같을꺼야/g, replace: "같을 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /것같아요/g, replace: "것 같아요", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /것같습니다/g, replace: "것 같습니다", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /것같다/g, replace: "것 같다", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /모르겟/g, replace: "모르겠", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /모르겟다/g, replace: "모르겠다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /모르겟어요/g, replace: "모르겠어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /모르겟어/g, replace: "모르겠어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /모르겟네/g, replace: "모르겠네", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /모를꺼/g, replace: "모를 거", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /모를꺼야/g, replace: "모를 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /모를께/g, replace: "모를게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /잇어/g, replace: "있어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /잇을/g, replace: "있을", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /잇엇/g, replace: "있었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /없엇/g, replace: "없었", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /없엇다/g, replace: "없었다", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /없엇어/g, replace: "없었어", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /없엇어요/g, replace: "없었어요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /없을꺼야/g, replace: "없을 거야", reason: "띄어쓰기", confidence: defaultConfidence },
  { pattern: /없을꺼지/g, replace: "없을 거지", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /없을껄/g, replace: "없을걸", reason: "맞춤법", confidence: 0.6 },
  { pattern: /될껄/g, replace: "될걸", reason: "맞춤법", confidence: 0.6 },
  { pattern: /할껄/g, replace: "할걸", reason: "맞춤법", confidence: 0.6 },
  { pattern: /갈껄/g, replace: "갈걸", reason: "맞춤법", confidence: 0.6 },
  { pattern: /될껍니다/g, replace: "될 겁니다", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /할껍니다/g, replace: "할 겁니다", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /됬구나/g, replace: "됐구나", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫구나/g, replace: "됐구나", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬군/g, replace: "됐군", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫군/g, replace: "됐군", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬나/g, replace: "됐나", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫나/g, replace: "됐나", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫네/g, replace: "됐네", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬네/g, replace: "됐네", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됬을까/g, replace: "됐을까", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /됫을까/g, replace: "됐을까", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /시켜줄께/g, replace: "시켜줄게", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /시켜줄께요/g, replace: "시켜줄게요", reason: "맞춤법", confidence: defaultConfidence },
  { pattern: /안되요/g, replace: "안 돼요", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안되서/g, replace: "안 돼서", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안되도/g, replace: "안 돼도", reason: "맞춤법", confidence: 0.6 },
  { pattern: /안되니까/g, replace: "안 되니까", reason: "띄어쓰기", confidence: 0.6 },
  { pattern: /왠만한/g, replace: "웬만한", reason: "맞춤법", confidence: 0.6 },
  { pattern: /왠만하면/g, replace: "웬만하면", reason: "맞춤법", confidence: 0.6 },
];

export function applyRuleSuggestions(text: string) {
  const suggestions: Array<{
    start: number;
    end: number;
    before: string;
    after: string;
    reason: string;
    confidence?: number;
  }> = [];

  spellcheckRules.forEach((rule) => {
    const pattern = rule.pattern.global
      ? rule.pattern
      : new RegExp(rule.pattern.source, `${rule.pattern.flags}g`);
    const matches = text.matchAll(pattern);
    for (const match of matches) {
      if (!match[0]) continue;
      const start = match.index ?? -1;
      if (start < 0) continue;
      const end = start + match[0].length;
      const after = match[0].replace(rule.pattern, rule.replace);
      if (after === match[0]) continue;
      suggestions.push({
        start,
        end,
        before: match[0],
        after,
        reason: rule.reason,
        confidence: rule.confidence ?? defaultConfidence,
      });
    }
  });

  return suggestions;
}
