"use client";
import { useState } from "react";
import { archiveRequest, type Library } from "./types";
import { Button, Field, inputClass, Notice } from "./ui";
type Preview = { rows: { rowNumber: number; releaseTitle: string; trackTitle: string; errors: string[]; duplicate: boolean }[]; totalRows: number; validRows: number; errorCount: number; duplicateCount: number };
export const csvHeader = "release_key,release_title,release_type,release_date,track_key,track_title,disc_number,track_number,version,artist_name,isrc,work_key,work_title,writers,iswc";
export function CsvImport({ library, onImported }: { library: Library; onImported: (library: Library) => void }) {
  const [csv, setCsv] = useState(csvHeader + "\n"); const [preview, setPreview] = useState<Preview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(importRows: boolean) { setBusy(true); setError(""); try { const result = await archiveRequest<{ preview: Preview; library: Library }>("", { action: importRows ? "csv-import" : "csv-preview", libraryId: library.id, version: library.version, csv }); if (importRows) onImported(result.library); else setPreview(result.preview); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="space-y-4"><Notice>사용 권한이 있는 유통 자료만 가져와 주세요. release_key·track_key는 유통 자료에서 일관되게 사용하는 고유 키입니다. 같은 제목을 자동 병합하지 않으며 같은 키로 다시 가져온 항목은 중복으로 표시합니다.</Notice><Field label="CSV 파일 (UTF-8, 최대 400 KB)"><input className={inputClass} type="file" accept=".csv,text/csv" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 400000) { setError("CSV 파일은 400 KB 이하여야 합니다."); return; } setCsv(await file.text()); setPreview(null); setError(""); }} /></Field><Field label="CSV 내용" hint="발매 형식: album / ep / single / other. 제공받지 않은 ISRC·ISWC는 비워 두세요."><textarea className={`${inputClass} font-mono text-xs`} rows={8} value={csv} onChange={(e) => { setCsv(e.target.value); setPreview(null); }} /></Field>{error && <Notice error>{error}</Notice>}<Button onClick={() => void submit(false)} disabled={busy}>가져오기 전 미리보기</Button>{preview && <section className="space-y-3" aria-label="CSV 행별 미리보기"><p className="text-sm font-bold">전체 {preview.totalRows}행 · 유효 {preview.validRows}행 · 중복 {preview.duplicateCount}행 · 오류 {preview.errorCount}행</p><div className="max-h-80 space-y-2 overflow-y-auto">{preview.rows.map((row) => <div key={row.rowNumber} className="rounded-lg border border-border p-3 text-sm"><strong>{row.rowNumber}행 · {row.releaseTitle} / {row.trackTitle}</strong><p>{row.duplicate ? "기존 키와 중복 — 건너뜀" : "새 항목"}</p>{row.errors.map((error) => <p className="text-red-700 dark:text-red-300" key={error}>{error}</p>)}</div>)}</div><Button primary disabled={busy || preview.errorCount > 0 || preview.validRows === 0} onClick={() => void submit(true)}>미리 본 유효 항목 가져오기</Button></section>}</div>;
}
