"use client";
import { useState } from "react";
import { kindLabels, statusLabels, resultLabels, sourceLabels, queryStatusLabels, type ArchiveData, type ArchiveTask, type ArchiveTaskFields, type ArchiveTrack, type ArchiveCommand } from "@/lib/music-archive/model";
import type { AgencyGuide } from "@/lib/music-archive/guides";
import { Badge, Button, Field, Notice, External, inputClass } from "./ui";

const agencies: Record<ArchiveTask["kind"], string[]> = { review: ["KBS", "MBC", "SBS", "기타 방송사"], copyright_work: ["KOMCA", "KOSCAP", "기타 관리기관"], copyright_legal: ["한국저작권위원회"], performer: ["한국음악실연자연합회", "기타 실연자 기관"], karaoke: ["TJ", "금영"] };
const results: Record<ArchiveTask["kind"], ArchiveTask["result"][]> = { review: ["unknown", "eligible", "ineligible", "rejected"], copyright_work: ["unknown", "information_found", "approved", "rejected"], copyright_legal: ["unknown", "information_found", "approved", "rejected"], performer: ["unknown", "information_found", "approved", "rejected"], karaoke: ["unknown", "listed", "not_listed", "rejected"] };

export function TaskEditor({ data, tracks, kind, initial, busy, onSave }: { data: ArchiveData; tracks: ArchiveTrack[]; kind: ArchiveTask["kind"]; initial?: ArchiveTask; busy: boolean; onSave: (command: ArchiveCommand) => Promise<void> }) {
  const [selected, setSelected] = useState<string[]>(initial ? [initial.trackId] : tracks.filter((track) => track.managed && !track.excluded && !track.mergedInto).map((track) => track.id).slice(0, 200));
  const [values, setValues] = useState<ArchiveTaskFields>(() => initial ? {
    kind: initial.kind, agency: initial.agency, status: initial.status, result: initial.result, participant: initial.participant, role: initial.role, executor: initial.executor, agencyName: initial.agencyName, recordingId: initial.recordingId, workId: initial.workId, applicationDate: initial.applicationDate, completedDate: initial.completedDate, checkedDate: initial.checkedDate, recheckDate: initial.recheckDate, referenceNumber: initial.referenceNumber, songNumber: initial.songNumber, applicationUrl: initial.applicationUrl, memo: initial.memo, attachmentIds: initial.attachmentIds,
  } : { kind, agency: agencies[kind][0], status: "needs_check", result: "unknown", executor: "self", attachmentIds: [] });
  const [preview, setPreview] = useState(false);
  const [error, setError] = useState("");
  const set = <K extends keyof ArchiveTaskFields>(key: K, value: ArchiveTaskFields[K]) => setValues((old) => ({ ...old, [key]: value }));
  const textInput = (key: keyof ArchiveTaskFields, label: string, type = "text", hint?: string) => <Field label={label} hint={hint}><input className={inputClass} type={type} value={String(values[key] ?? "")} maxLength={key === "applicationUrl" ? 2000 : 500} onChange={(e) => setValues((old) => ({ ...old, [key]: e.target.value || undefined }))} /></Field>;
  async function save() {
    setError("");
    try { await onSave(initial ? { type: "update_task", taskId: initial.id, patch: values } : { type: "save_tasks", id: crypto.randomUUID(), trackIds: selected, task: values }); }
    catch (e) { setError((e as Error).message); }
  }
  return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (preview) void save(); else setPreview(true); }}>
    <Notice>업무 진행·결과·조회 여부는 별개입니다. 저장한 완료 기록은 “사용자 입력”으로 표시되며 기관 확인이나 실제 수록을 인증하지 않습니다. 신청 페이지 방문으로 상태가 바뀌지 않습니다.</Notice>
    {error && <Notice error>{error}</Notice>}
    {preview ? <section className="space-y-3" aria-label="선택 트랙 적용 미리보기"><h3 className="font-bold">적용할 범위를 확인해 주세요</h3><p>{kindLabels[values.kind]} / {values.agency} · {statusLabels[values.status ?? "needs_check"]} · {resultLabels[values.result ?? "unknown"]}</p><p className="text-sm">참여자: {values.participant || "미기록"} / 역할: {values.role || "미기록"}</p><ul className="list-disc space-y-1 pl-5 text-sm">{tracks.filter((track) => selected.includes(track.id)).map((track) => <li key={track.id}>{track.discNumber}-{track.trackNumber}. {track.title} · {track.version || "버전 미기록"}</li>)}</ul><Notice>선택한 {selected.length}개 트랙에만 {initial ? "기존 기록을 수정" : "업무 이력을 추가"}합니다. 다른 기관·참여자·녹음 버전으로 결과가 전파되지 않습니다.</Notice><div className="flex flex-wrap gap-2"><Button onClick={() => setPreview(false)}>입력 수정</Button><Button type="submit" primary disabled={busy || !selected.length}>{busy ? "저장 중" : "확인한 범위에 저장"}</Button></div></section> : <>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="업무 종류"><select className={inputClass} value={values.kind} onChange={(e) => { const next = e.target.value as ArchiveTask["kind"]; setValues((old) => ({ ...old, kind: next, agency: agencies[next][0], result: "unknown" })); }}>{Object.entries(kindLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="기관 / 방송사 / 업체"><input className={inputClass} list="archive-agency-options" value={values.agency} onChange={(e) => set("agency", e.target.value)} required maxLength={500} /><datalist id="archive-agency-options">{agencies[values.kind].map((agency) => <option key={agency} value={agency} />)}</datalist></Field><Field label="업무 진행 상태"><select className={inputClass} value={values.status} onChange={(e) => set("status", e.target.value as ArchiveTask["status"])}>{Object.entries(statusLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="업무 결과"><select className={inputClass} value={values.result} onChange={(e) => set("result", e.target.value as ArchiveTask["result"])}>{results[values.kind].map((key) => <option key={key} value={key}>{resultLabels[key]}</option>)}</select></Field><Field label="진행 주체"><select className={inputClass} value={values.executor ?? "self"} onChange={(e) => set("executor", e.target.value as ArchiveTask["executor"])}><option value="self">본인 직접 진행</option><option value="agency">다른 대행사</option><option value="onside">온사이드 (수동 기록)</option></select></Field>{textInput("agencyName", "대행사명 / 담당 주체")}{textInput("participant", "저작자 / 실연 참여자명")}{textInput("role", "역할 / 참여 부문", "text", "예: 작사, 작곡, 보컬, 코러스, 기타. 관리 권한이 있는 참여자만 기록해 주세요.")}
      <Field label="연결된 저작물"><select className={inputClass} value={values.workId ?? ""} onChange={(e) => set("workId", e.target.value || undefined)}><option value="">선택하지 않음</option>{data.works.map((work) => <option value={work.id} key={work.id}>{work.title} · {work.writers || "저작자 미기록"} · {work.iswc || "ISWC 없음"}</option>)}</select></Field><Field label="적용 녹음 버전"><select className={inputClass} value={values.recordingId ?? ""} onChange={(e) => set("recordingId", e.target.value || undefined)}><option value="">각 트랙의 버전 기준</option>{data.recordings.map((recording) => <option value={recording.id} key={recording.id}>{recording.title} · {recording.version || "버전 미기록"} · {recording.isrc || "ISRC 없음"}</option>)}</select></Field>
      {textInput("applicationDate", "신청일", "date")}{textInput("completedDate", "처리일 / 등록일", "date")}{textInput("checkedDate", "결과 확인일", "date")}{textInput("recheckDate", "다시 확인할 날짜", "date")}{textInput("referenceNumber", "접수 / 등록 / 작품 확인번호")}{values.kind === "karaoke" && textInput("songNumber", "수록곡 번호")}{textInput("applicationUrl", "신청 / 공식 조회 근거 URL", "url")}</div>
      <Field label={values.kind === "karaoke" ? "신청 방식 (일반 신청 / 유료 등록) 및 메모" : "메모 / 보완 요청 / 확인 근거"}><textarea className={inputClass} rows={3} value={values.memo ?? ""} onChange={(e) => set("memo", e.target.value)} maxLength={4000} /></Field>
      <fieldset className="space-y-2 rounded-lg border border-border p-3"><legend className="px-1 text-sm font-bold">적용 트랙 선택 ({selected.length}곡 / 최대 200곡)</legend>{tracks.map((track) => <label key={track.id} className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(track.id)} disabled={!!initial || !track.managed || track.excluded || !!track.mergedInto} onChange={(e) => setSelected((old) => e.target.checked ? [...old, track.id].slice(0, 200) : old.filter((id) => id !== track.id))} /><span>{track.discNumber}-{track.trackNumber}. {track.title} · {track.version || "버전 미기록"}{!track.managed && " (관리 대상 아님)"}</span></label>)}</fieldset>
      <p className="text-xs leading-5 text-muted-foreground">증빙은 기록 저장 후 첨부할 수 있습니다. 외부기관 비밀번호·인증서·신분증은 해당 기관에 직접 제출해 주세요.</p><Button type="submit" primary disabled={!selected.length || busy}>선택한 트랙에 적용할 내용 확인</Button>
    </>}
  </form>;
}

export function TaskBadges({ task }: { task: ArchiveTask }) { return <div className="flex flex-wrap gap-1.5"><Badge attention={["needs_check","needs_changes"].includes(task.status)}>{statusLabels[task.status]}</Badge><Badge>{resultLabels[task.result]}</Badge><Badge>{sourceLabels[task.source]}</Badge><Badge>{queryStatusLabels[task.queryStatus]}</Badge></div>; }

export function Guides({ guides, kind }: { guides: AgencyGuide[]; kind: "review" | "copyright" | "performer" | "karaoke" }) {
  return <section className="space-y-3" aria-label="공식 등록 방법 안내"><h3 className="font-black">등록 방법과 공식 안내</h3>{guides.filter((guide) => guide.visible && guide.kind === kind).map((guide) => <details key={guide.id} className="rounded-lg border border-border bg-background p-3"><summary className="cursor-pointer text-sm font-bold">{guide.name} · 등록 방법 보기</summary><div className="mt-3 space-y-3 text-sm leading-6"><p>{guide.introduction}</p><p><strong>누가 확인하나요: </strong>{guide.eligibility}</p><div><strong>준비할 정보</strong><ul className="list-disc pl-5">{guide.preparation.map((item) => <li key={item}>{item}</li>)}</ul></div><div><strong>공식 신청 경로</strong><ol className="list-decimal pl-5">{guide.steps.map((item) => <li key={item}>{item}</li>)}</ol></div><div><strong>신청 후 확인 / 온사이드 기록</strong><ul className="list-disc pl-5">{guide.after.map((item) => <li key={item}>{item}</li>)}</ul></div><Notice>{guide.costNote}</Notice><div className="flex flex-wrap gap-x-4 gap-y-1">{guide.searchUrl && <External href={guide.searchUrl}>공식 정보 조회</External>}<External href={guide.applyUrl || guide.url}>공식 사이트에서 신청</External></div><p className="text-xs text-muted-foreground">외부기관에 직접 진행합니다. 온사이드가 제휴·대행하거나 이 화면에서 제출하지 않습니다. 공식 출처 확인일: {guide.checkedAt}</p><div className="flex flex-wrap gap-x-3">{guide.sources.map((source) => <External key={source.url} href={source.url}>{source.title}</External>)}</div></div></details>)}{!guides.some((guide) => guide.visible && guide.kind === kind) && <Notice>현재 노출 중인 공식 안내가 없습니다. 관리자에게 링크 확인을 요청할 수 있으며 업무 기록은 사용할 수 있습니다.</Notice>}</section>;
}
