// Centralized submission select clauses to avoid missing-column errors.
// Include only columns confirmed to exist in the current DB schema.

export const SUBMISSION_USER_DETAIL_SELECT = [
  "id",
  "user_id",
  "artist_id",
  "title",
  "artist_name",
  "artist_name_kr",
  "artist_name_en",
  "type",
  "status",
  "payment_status",
  "payment_method",
  "amount_krw",
  "certificate_b2_path",
  "certificate_original_name",
  "certificate_mime",
  "certificate_size",
  "certificate_uploaded_at",
  "created_at",
  "updated_at",
  "mv_desired_rating",
  "package:packages ( name, station_count, price_krw )",
].join(", ");

export const SUBMISSION_ADMIN_DETAIL_SELECT = [
  "id",
  "user_id",
  "title",
  "artist_name",
  "artist_name_kr",
  "artist_name_en",
  "status",
  "payment_status",
  "payment_method",
  "amount_krw",
  "mv_base_selected",
  "mv_desired_rating",
  "certificate_b2_path",
  "certificate_original_name",
  "certificate_mime",
  "certificate_size",
  "certificate_uploaded_at",
  "pre_review_requested",
  "karaoke_requested",
  "bank_depositor_name",
  "admin_memo",
  "result_status",
  "result_memo",
  "result_notified_at",
  "applicant_email",
  "applicant_name",
  "applicant_phone",
  "created_at",
  "updated_at",
  "type",
  "package:packages ( name, station_count, price_krw )",
  // Album extras
  "release_date",
  "genre",
  "distributor",
  "production_company",
  "previous_release",
  "artist_type",
  "artist_gender",
  "artist_members",
  "is_oneclick",
  "melon_url",
  // MV extras
  "mv_runtime",
  "mv_format",
  "mv_director",
  "mv_lead_actor",
  "mv_storyline",
  "mv_production_company",
  "mv_agency",
  "mv_album_title",
  "mv_production_date",
  "mv_distribution_company",
  "mv_business_reg_no",
  "mv_usage",
  "mv_memo",
  "mv_song_title",
  "mv_song_title_kr",
  "mv_song_title_en",
  "mv_song_title_official",
  "mv_composer",
  "mv_lyricist",
  "mv_arranger",
  "mv_song_memo",
  "mv_lyrics",
  // relations
  "album_tracks ( id, track_no, track_title, track_title_kr, track_title_en, track_title_official, featuring, composer, lyricist, arranger, lyrics, notes, is_title, title_role, broadcast_selected )",
  // guest fields (nullable; may not exist in older DBs)
  "guest_name",
  "guest_company",
  "guest_email",
  "guest_phone",
].join(", ");
